# Generated by Django 4.2.1 on 2023-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=30, unique=True, verbose_name="아이디"),
                ),
                ("password", models.CharField(max_length=30, verbose_name="비밀번호")),
                (
                    "name",
                    models.CharField(default="", max_length=30, verbose_name="이름"),
                ),
                (
                    "birth",
                    models.DateField(
                        blank=True, max_length=30, null=True, verbose_name="생일"
                    ),
                ),
                ("is_subscribe", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
