# Generated by Django 4.2.1 on 2023-08-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_subscribe",
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_subscribe", models.BooleanField(default=False)),
                (
                    "sub_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="구독만료날짜"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
