# Generated by Django 4.2.1 on 2023-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_is_subscribe_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="sub_start",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="구독만료날짜"
            ),
        ),
    ]
