# Generated by Django 4.2.1 on 2023-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_subscribe_sub_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribe",
            name="sub_end",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="구독만료날짜"
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="sub_start",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="구독시작날짜"
            ),
        ),
    ]
