# Generated by Django 4.2.1 on 2023-08-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_subscribe_is_subscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="is_subscribe",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="구독여부"
            ),
        ),
    ]
