# Generated by Django 4.2.1 on 2023-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_subscribe_is_subscribe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=30, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=30, verbose_name="비밀번호"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=30, unique=True, verbose_name="아이디"),
        ),
    ]
