# Generated by Django 4.2.1 on 2023-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_user_email_alter_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="sub_end",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="구독만료날짜"
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="sub_start",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="구독시작날짜"
            ),
        ),
    ]
