# Generated by Django 4.2.1 on 2023-08-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_subscribe_sub_end_alter_subscribe_sub_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=300, verbose_name="비밀번호"),
        ),
    ]
