# Generated by Django 4.2.1 on 2023-08-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_quest_do",
            field=models.BooleanField(default=False, verbose_name="퀘스트수행여부"),
        ),
    ]
