# Generated by Django 4.2.1 on 2023-08-17 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_is_quest_do"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "save",
                    models.JSONField(
                        blank=True, max_length=1000, null=True, verbose_name="임시저장"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
