# Generated by Django 4.2.1 on 2023-08-17 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_temporarystorage_save"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TemporaryStorage",
        ),
    ]
