# Generated by Django 4.2.1 on 2023-08-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_tempstorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempstorage",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
