# Generated by Django 4.2.1 on 2023-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mcdonald",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=30, verbose_name="메뉴이름")),
                (
                    "image",
                    models.URLField(max_length=500, null=True, verbose_name="메뉴이미지"),
                ),
                ("price", models.IntegerField(verbose_name="가격")),
                ("calorie", models.CharField(max_length=30, verbose_name="칼로리")),
                (
                    "menu_category",
                    models.CharField(max_length=30, verbose_name="메뉴카테고리"),
                ),
                (
                    "food_category",
                    models.CharField(max_length=30, null=True, verbose_name="음식카테고리"),
                ),
                (
                    "menu_size",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="사이즈"
                    ),
                ),
                ("is_set", models.BooleanField(verbose_name="세트여부")),
            ],
        ),
    ]
