# Generated by Django 4.2.1 on 2023-08-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("burgers", "0002_setmenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="setmenu",
            name="signle_menu",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_menus",
                to="burgers.mcdonald",
            ),
            preserve_default=False,
        ),
    ]
