# Generated by Django 4.2.1 on 2023-08-05 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("burgers", "0003_setmenu_signle_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setmenu",
            old_name="signle_menu",
            new_name="single_menu",
        ),
    ]
