# Generated by Django 4.2.1 on 2023-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("burgers", "0004_rename_signle_menu_setmenu_single_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcdonald",
            name="is_happy",
            field=models.BooleanField(default=False, verbose_name="해피스낵여부"),
        ),
    ]
