# Generated by Django 4.2.1 on 2023-08-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("burgers", "0005_mcdonald_is_happy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=30, verbose_name="메뉴이름")),
                (
                    "image",
                    models.URLField(max_length=500, null=True, verbose_name="메뉴이미지"),
                ),
                ("price", models.IntegerField(verbose_name="가격")),
                ("calorie", models.CharField(max_length=30, verbose_name="칼로리")),
                (
                    "menu_size",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="사이즈"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="mcdonald",
            name="is_set",
        ),
        migrations.AddField(
            model_name="mcdonald",
            name="is_detail",
            field=models.BooleanField(default=False, verbose_name="디테일여부"),
        ),
        migrations.DeleteModel(
            name="SetMenu",
        ),
        migrations.AddField(
            model_name="detailmenu",
            name="single_menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail_menus",
                to="burgers.mcdonald",
            ),
        ),
    ]
