# Generated by Django 4.2.1 on 2023-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "burgers",
            "0006_detailmenu_remove_mcdonald_is_set_mcdonald_is_detail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detailmenu",
            name="menu_category",
            field=models.CharField(default="", max_length=30, verbose_name="메뉴카테고리"),
            preserve_default=False,
        ),
    ]
