# Generated by Django 4.2.1 on 2023-08-11 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True, max_length=300, null=True, verbose_name="퀘스트내용"
                    ),
                ),
                ("is_do", models.BooleanField(default=False, verbose_name="퀘스트수행여부")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
