# Generated by Django 4.2.1 on 2023-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="is_accept",
            field=models.BooleanField(default=False, verbose_name="퀘스트수락여부"),
        ),
    ]
