# Generated by Django 4.2.1 on 2023-08-16 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quests", "0002_quest_is_accept"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="is_do",
        ),
    ]
