# Generated by Django 4.2.1 on 2023-08-16 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quests", "0003_remove_quest_is_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
