# Generated by Django 4.2.1 on 2023-08-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "start_terminal",
                    models.CharField(default="", max_length=255, null=True),
                ),
                (
                    "arrive_terminal",
                    models.CharField(default="", max_length=255, null=True),
                ),
                ("start_time", models.CharField(max_length=255)),
                ("required_time", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("rate", models.CharField(max_length=255)),
                ("rest_seat", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("train_name", models.CharField(max_length=255)),
                ("start_station", models.CharField(max_length=255)),
                ("arrive_station", models.CharField(max_length=255)),
                ("start_time", models.CharField(max_length=255)),
                ("arrive_time", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
            ],
        ),
    ]
