# Generated by Django 4.2.4 on 2023-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgvmovie',
            name='movie_poster',
            field=models.URLField(),
        ),
    ]
