# Generated by Django 4.2.1 on 2023-08-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theaters", "0002_alter_cgvmovie_movie_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cgvmovie",
            name="max_seat",
        ),
        migrations.RemoveField(
            model_name="cgvmovie",
            name="seat_number",
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField()),
                ("max_seat", models.IntegerField(default=100)),
                ("time", models.CharField(max_length=30, verbose_name="영화시간")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="theaters.cgvmovie",
                    ),
                ),
            ],
        ),
    ]
