# Generated by Django 4.2.1 on 2023-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=50, verbose_name="옵션항목")),
                ("price", models.IntegerField(verbose_name="옵션가격")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="option_images/",
                        verbose_name="옵션이미지",
                    ),
                ),
                ("explanation", models.CharField(max_length=100, verbose_name="설명")),
            ],
        ),
        migrations.AddField(
            model_name="coffeemenu",
            name="Detail_page",
            field=models.BooleanField(default=False, verbose_name="상세페이지유무"),
        ),
        migrations.AddField(
            model_name="coffeemenu",
            name="menu_categoty",
            field=models.CharField(default="", max_length=30, verbose_name="메뉴카테고리"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coffeemenu",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="coffee_images/", verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="coffeemenu",
            name="name",
            field=models.CharField(max_length=30, verbose_name="메뉴이름"),
        ),
        migrations.AlterField(
            model_name="coffeemenu",
            name="price",
            field=models.IntegerField(verbose_name="가격"),
        ),
    ]
