# Generated by Django 4.2.1 on 2023-08-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0002_menudetail_coffeemenu_detail_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeemenu",
            name="brand_categoty",
            field=models.CharField(default="", max_length=30, verbose_name="브랜드이름"),
            preserve_default=False,
        ),
    ]
