# Generated by Django 4.2.1 on 2023-08-07 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0003_coffeemenu_brand_categoty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coffeemenu",
            old_name="brand_categoty",
            new_name="brand_category",
        ),
        migrations.RenameField(
            model_name="coffeemenu",
            old_name="menu_categoty",
            new_name="menu_category",
        ),
    ]
