# Generated by Django 4.2.1 on 2023-08-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0004_rename_brand_categoty_coffeemenu_brand_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menudetail",
            name="CoffeeMenu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coffee_api.coffeemenu",
            ),
        ),
    ]
