# Generated by Django 4.2.1 on 2023-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0005_menudetail_coffeemenu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudetail",
            name="explanation",
        ),
        migrations.AddField(
            model_name="coffeemenu",
            name="explanation",
            field=models.CharField(default="", max_length=100, verbose_name="설명"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menudetail",
            name="option",
            field=models.CharField(max_length=50, verbose_name="옵션이름"),
        ),
    ]
