# Generated by Django 4.2.1 on 2023-08-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "coffee_api",
            "0006_remove_menudetail_explanation_coffeemenu_explanation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffeemenu",
            name="brand_category",
        ),
        migrations.AddField(
            model_name="coffeemenu",
            name="type",
            field=models.CharField(default="", max_length=30, verbose_name="타입"),
            preserve_default=False,
        ),
    ]
