# Generated by Django 4.2.1 on 2023-08-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee_api", "0007_remove_coffeemenu_brand_category_coffeemenu_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudetail",
            name="CoffeeMenu",
        ),
        migrations.AddField(
            model_name="menudetail",
            name="type",
            field=models.CharField(default="", max_length=30, verbose_name="타입"),
            preserve_default=False,
        ),
    ]
